### ISSUE TITLE
Support netstandard2.0

### ISSUE THREAD

**Issue by johannesegger** [Slion/SharpLibWin32#3]
The NuGet package and the project currently target `net20`. So when referencing this project from a `netstandard` library or in my case a `netcoreapp` app you always get the following warning:

> warning NU1701: Package 'SharpLibWin32 0.2.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.

Any chance that you add a netstandard target? Do you need net20 at all? I think I could create a PR quite quickly that drops net20 support and instead targets netstandard2.0 (if the library is fully compatible with netstandard2.0 which I'm not sure about).

**Comment by Slion** [comment]
I sure welcome PR. I've never published packages supporting multiple target or architecture so I'll have to trust you on that one too.

**Comment by Slion** [comment]
I guess I would need to setup the build server to build those targets too.

**Comment by Slion** [comment]
I wonder if you have to create one solution for each framework version you want to target.

**Comment by johannesegger** [comment]
I think you can specify multiple targets within the csproj file (at least with the new-style csproj format - see https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#implicit-package-references). I'm not sure about any changes on the build server though.

**Comment by johannesegger** [comment]
We should continue discussion at #4.
